### ISSUE TITLE
Replicate backup job to other namespaces

### ISSUE THREAD

**Issue by konigpeter** [RocketChat/k8s-secrets-backup#3]
Hello, 
Congratulations on a fantastic job.

I was able to successfully execute following the example.

Now I'm trying to backup a "production" namespace, but I'm having problems, I believe I must have replaced "kube-system" with "production".

Could you tell me which kinds I need to change from "kube-system" to "production"?

**Comment by LuluGO** [comment]
Hey, sorry for the very late reply.

- you should change in the cronjob the env variable namespace and put production
- then create a role in the production namespace with access to secrets (you don't need configmaps like in the example because the access to configmap is only for naming the file with the cluster name, and that configmap you have it created in the kube-system namespace)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-sentinel-production
  namespace: production
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]
```
-  and the role binding for that role in the production namespace too
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-sentinel-production
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-sentinel-production
subjects:
- kind: ServiceAccount
  name: sealed-secrets-keys-sentinel
  namespace: operations
```
I think that should be enough, assuming you still have the access to the configmap cluster-info configured
